# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Windows版

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Install dependencies # 使用pip安装项目的依赖项
        run: |
          pip install requests pycryptodome unicodedata
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          spec: '教务系统.py'
          upload_exe_with_name: '教务系统'
          options: --onefile, --name "教务系统", --windowed, 
